### ISSUE TITLE
[CTD] When loading a new world

### ISSUE THREAD

**Issue by drakray** [TheCBProject/EnderStorage#105]
MC 1.12.2
Forge 2824
ES 135 and 136 tested, same crash
https://pastebin.com/j9GfrEj8
```
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at codechicken.enderstorage.network.TankSynchroniser.onPlayerLogin(TankSynchroniser.java:232)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1712_TankSynchroniser_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by drakray** [comment]
Well, tested something else(removing EnderStorage) and got this instead:
```

java.lang.NullPointerException: Ticking memory connection
	at hunternif.mc.atlas.ext.ExtBiomeDataHandler.onPlayerLogin(ExtBiomeDataHandler.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2328_ExtBiomeDataHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
```
So problem has unknown source :(

**Comment by drakray** [comment]
Well, it might not be a ES trouble at all, as I tried anotherr World Type(was using a superflat, just tried BoP) and got https://pastebin.com/L809ng9p
```
java.lang.NullPointerException: Unexpected error
	at baubles.api.BaublesApi.getBaublesHandler(BaublesApi.java:21)
	at com.rwtema.extrautils2.modcompat.XUCompatBaubles.lambda$static$0(XUCompatBaubles.java:21)
	at com.rwtema.extrautils2.utils.helpers.PlayerHelper.lambda$getAllPlayerItems$1(PlayerHelper.java:75)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.rwtema.extrautils2.utils.helpers.PlayerHelper.getAllPlayerItems(PlayerHelper.java:75)
	at com.rwtema.extrautils2.power.ClientPower.playerPowerManagerTick(ClientPower.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1832_ClientPower_playerPowerManagerTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
So maybe it's a forge/java thing?
I'm trying updating Java, as I can't update forge for now :(
