### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by VariableVixen** [TheCBProject/EnderStorage#126]
I'm on version 2.4.5.135 from the DW20 pack for 1.12.2, slightly modified. After using Carry On to move an ender tank a few times with no issues, I did it again and this time crashed completely as soon as I tried to place the tank down. After loading my game again, I tried to enter the world and crashed again with the exact same error ([full crashlog](https://paste.ee/p/nbetZ)):

```
java.lang.ArrayIndexOutOfBoundsException: 7
	at codechicken.enderstorage.tile.TileEnderTank.getIndexedCuboids(TileEnderTank.java:243)
	at codechicken.enderstorage.block.BlockEnderStorage.func_180636_a(BlockEnderStorage.java:197)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:473)
	at net.minecraft.world.World.func_147447_a(World.java:1087)
	at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:491)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1718)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
```

**Comment by covers1624** [comment]
This was fixed, Update EnderStorage.
