### ISSUE TITLE
Crash on startup [1.19]

### ISSUE THREAD

**Issue by Speiger** [TheCBProject/EnderStorage#192]
```
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: enderstorage:textures/EnderPouch.psd
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.19-20220607.102129-srg.jar%23141!/:?] {re:mixin,re:classloading,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.19-20220607.102129-srg.jar%23141!/:?] {re:mixin,re:classloading,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraftforge.resource.PathResourcePack.lambda$getResources$1(PathResourcePack.java:116) ~[forge-1.19-41.0.62-universal.jar%23146!/:?] {re:classloading}
```

Started my 1.19 IC2C beta and this is instantly a crashreport.
While this can be caused by another mod it isn't a good idea to have a invalid name "resource" in the final jar...
Would be a good idea to remove/lowercase the filename to prevent crashes like these.

Small edit: this is the code i am running that causes the crash... 
```java
for(Map.Entry<ResourceLocation, Resource> entry : manager.listResources("textures", T -> T.getPath().endsWith("texture_package.json")).entrySet())
{
}
```

**Comment by covers1624** [comment]
Fixed in https://github.com/TheCBProject/EnderStorage/commit/ac4bc4366b20a12026933da17140b3897a8675f3

Build: [1.19-2.10.0.179](https://maven.covers1624.net/codechicken/EnderStorage/1.19-2.10.0.179/EnderStorage-1.19-2.10.0.179-universal.jar)
