### ISSUE TITLE
Game Crash when viewing uses for Ender Pouch in JEI

### ISSUE THREAD

**Issue by Nataly171** [TheCBProject/EnderStorage#194]
I've found that the game stalls out and crashes when I try to view the recipes using the Ender Pouch in JEI, that is, pressing "U" while hovering over the Ender Pouch in my inventory or in the JEI gui.

Minecraft Version: 1.18.2
Forge Version: 40.1.60
Ender Storage Version: 2.9.0.177
CodeChicken Lib Version: 4.1.1.462
JEI Version: 9.7.0.209

The crash report is attached below.

[crash-2022-07-13_03.04.43-client.txt](https://github.com/TheCBProject/EnderStorage/files/9100228/crash-2022-07-13_03.04.43-client.txt)

**Comment by covers1624** [comment]
```

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?] {}
	at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[client-1.18.2-20220404.173914-srg.jar%23110!/:?] {re:mixin,re:classloading}
	at com.simibubi.create.compat.jei.category.MechanicalCraftingCategory.draw(MechanicalCraftingCategory.java:104) ~[create-mc1.18.2_v0.5.0c.jar%2368!/:mc1.18.2_v0.5.0c] {re:classloading}
	at com.simibubi.create.compat.jei.category.MechanicalCraftingCategory.draw(MechanicalCraftingCategory.java:35) ~[create-mc1.18.2_v0.5.0c.jar%2368!/:mc1.18.2_v0.5.0c] {re:classloading}
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:167) ~[jei-1.18.2-9.7.0.209.jar%2383!/:9.7.0.209] {re:classloading,re:mixin}
	at mezz.jei.gui.recipes.RecipesGui.m_6305_(RecipesGui.java:245) ~[jei-1.18.2-9.7.0.209.jar%2383!/:9.7.0.209] {re:classloading}
```

Please report this issue to Mechanical Crafting.

EnderStorage is in no way involved with this crash.
