### ISSUE TITLE
Crash during the common_setup

### ISSUE THREAD

**Issue by I3estOFF** [TheCBProject/EnderStorage#207]
![image](https://user-images.githubusercontent.com/63112899/210136553-6531c57d-7154-4ac8-a637-f0ca56c9d721.png)
[crash-2022-12-31_13.17.08-fml.txt](https://github.com/TheCBProject/EnderStorage/files/10327324/crash-2022-12-31_13.17.08-fml.txt)
[latest.log](https://github.com/TheCBProject/EnderStorage/files/10327325/latest.log)

**Comment by covers1624** [comment]
This is not an issue with EnderStorage, despite Forge claiming it is, apparently im stepping on a landmine.

Please report this issue to Random Patches or disable their Keep Alive changes in their config.

```
Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getKeepAlivePacketInterval(J)J in randompatches.mixins.json:timeouts.ServerPlayNetHandlerKeepAliveMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap randompatches.refmap.json
Stacktrace:
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {re:classloading,re:classloading}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
```
