### ISSUE TITLE
Inventory Tweaks combo bug

### ISSUE THREAD

**Issue by FloppyDingo** [TheCBProject/EnderStorage#33]
Just letting you know that there is a small bug involving Inventory Tweaks - not sure which end it's on (yours or theirs) so I'm posting this in both spots:

If a player's bag is full and they attempt to use invtweaks to shift+click an item into the bag, it'll crash and boot them offline; same for if their inventory is full and they attempt to pull an item out.

**Comment by FloppyDingo** [comment]
Sorry, forgot to note:

Minecraft Version: 1.11.2
EnderStorage Version: 2.3.0.112
InvTweaks Version: 1.62+beta.86

**Comment by Micman27** [comment]
same thing happens without invtweaks

**Comment by covers1624** [comment]
Crash report or it did not happen.

**Comment by FloppyDingo** [comment]
https://pastebin.com/uhXP8Mq1

Full crash report is at the pastebin above. Just the crash error is here:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  DummyPlugin (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar)
  DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta4-anarchy.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 5/2/17 10:00 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.inventory.Container.func_184996_a(Container.java:239)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:551)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Error is replicated by filling an enderbag, then attempting to shift+click another item - which is the shortcut invtweaks uses to place an item into a storage container. This causes an immediate crash.

**Comment by Medusalem** [comment]
Same over here : https://pastebin.com/qW0uA3Fb
Forge 13.20.0.2299
Ender storage: 2.3.0.112
