### ISSUE TITLE
[MC1.10.2][enderstorage 2.2.1.106] On player disconect I get this error

### ISSUE THREAD

**Issue by exultanthabit** [TheCBProject/EnderStorage#53]
[01:08:55] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_141]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at codechicken.enderstorage.network.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:236) ~[TankSynchroniser.class:?]
        at codechicken.enderstorage.network.EnderStorageSPH.handlePacket(EnderStorageSPH.java:17) ~[EnderStorageSPH.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:136) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler$1.run(PacketCustom.java:132) ~[PacketCustom$ServerInboundHandler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
[01:08:55] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_141]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at codechicken.enderstorage.network.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:236) ~[TankSynchroniser.class:?]
        at codechicken.enderstorage.network.EnderStorageSPH.handlePacket(EnderStorageSPH.java:17) ~[EnderStorageSPH.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:136) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler$1.run(PacketCustom.java:132) ~[PacketCustom$ServerInboundHandler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more

I get this every time I log out after placing and configuring tank/enderchests

MC: 1.10.2
Forge: 12.18.2422
Ender Storage: 1.10.2-2.2.1.106-universal

**Comment by covers1624** [comment]
Can you reproduce this on a 1.11 or 1.12 instance? 1.10 is no longer supported.

**Comment by covers1624** [comment]
Any more info on this?

**Comment by exultanthabit** [comment]
No, I run a modpack cant switch versions as quick as you guys discontinue versions

**Comment by covers1624** [comment]
My apologies for not putting more time out of my day to maintain 10 different projects across 3 minecraft versions.

**Comment by exultanthabit** [comment]
My issue wasn't the maintenance so much as tact, not even bothering to look at breaking bug because its 1.10 and furthering it by suggesting to just switch versions made it easy to just pass on the mod all together. (I know your time is your own and aren't compensated nearly enough, just tact could do with some work)

**Comment by covers1624** [comment]
Honestly my reply was in the heat of the moment, 1.10 is ainchent and noone should be on it 99.9 percent of mods should be updated to newer versions now, Even if i wanted to look in to the issue, my 1.10 workspace isnt functional anymore and i don't have time to set it back up again. So appologies for my harsh reply, but at times i don't think users actually understand how many projects i actively contribute to.. Its tough to manage time between them on the current version of mc, let allone accross 3 versions..
