### ISSUE TITLE
[1.12.2] Cannot sync an ender pouch with the color code of an ender chest when anarchyMode=true in the config

### ISSUE THREAD

**Issue by Captainaviator** [TheCBProject/EnderStorage#74]
I color coded my ender chest, and nothing happens when i sneak-right click on it with my ender pouch.
I'm running 1.12 now.  
Previous ticket for 1.11: https://github.com/TheCBProject/EnderStorage/issues/49

**Comment by DezziDez** [comment]
I am having this same issue.

**Comment by gigabit101** [comment]
Works fine so...
![2018-03-06_16-37-08](https://user-images.githubusercontent.com/5615438/37045021-e35984f4-215c-11e8-8b40-3bddbe6e13fb.gif)

**Comment by covers1624** [comment]
@Captainaviator Please provide a debug crash report (F3 + C for 10 seconds, then release.), If you are in an FTB Utils claimed area or any other sort of claimed / protected area, please exist that area and try again, if it still doesn't work, you will need to strip down your mods list, I'm unable to reproduce this in dev, or any of my custom packs, it is likely a mod in your pack causing the issue.

**Comment by Captainaviator** [comment]
Thanks, it appears there's more to this. Upon further testing, i was able to sync colors, but only if the chests were personalized (my apologies, i meant to update this ticket with that infirmation).  The other ticket i opened about not being able to use diamonds turned out to be a config setting where our server uses totems of undying instead of diamonds, so I'll have to test in SP more using default configs to confirm that issue

Either way, I'm not sure if it's intentional about the chest needing to be personalized before you can sync colors though, or if its a bug/mod conflict. I might have to dig further and try disabling even more mods to troubleshoot

**Comment by Captainaviator** [comment]
Thanks guys! I'm not using protected areas.  What mod packs have you tested in? That would greatly help me narrow down the mods to disable

**Comment by covers1624** [comment]
You should be able to sync a bag to the chests colour, whether it is locked or not. I can't actually provide my modlist as it contains many work in progress mods, but @gigabit101 may be able to provide his.

**Comment by gigabit101** [comment]
Mod list here https://gist.github.com/gigabit101/34c822d3baef131ceb1fd47086435df5

**Comment by covers1624** [comment]
Does your ingame name happen to have any interesting characters in it? Such as Unicode?

**Comment by covers1624** [comment]
Also, in anarchy mode, you can only sync the bag to chests you own. So, either that name check is failing due to interesting characters in your name, or you don't own the chest.

**Comment by Captainaviator** [comment]
Noted.  My in-game name is limited to normal English keyboard non-special non-numeric characters.  I am also only trying it on chests that I own and placed in the world

**Comment by covers1624** [comment]
The chest you are trying it on, is it 'personalised' to you? There is legit nothing here in the code that would suggest that you shouldn't be able to link them..

**Comment by Captainaviator** [comment]
By personalized, do you mean having a diamond/personalization item on the latch?

**Comment by covers1624** [comment]
Oh actually, i just read back the comments here, so it works on chests personalised to you but not on chests that aren't. Is there any exception in the server console when you attempt this?

**Comment by Captainaviator** [comment]
My admin didn't mention any

**Comment by covers1624** [comment]
Ahh, yep found the bug. Nullpointer thrown on the server that is caught and logged by mc.

**Comment by covers1624** [comment]
For reference:
```
[08:39:12] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.runTask(Util.java:51) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at codechicken.enderstorage.item.ItemEnderPouch.onItemUseFirst(ItemEnderPouch.java:60) ~[ItemEnderPouch.class:?]
	at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:200) ~[ItemStack.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:436) ~[PlayerInteractionManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:739) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:59) ~[CPacketPlayerTryUseItemOnBlock.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:1) ~[CPacketPlayerTryUseItemOnBlock.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_171]
	at net.minecraft.util.Util.runTask(Util.java:50) ~[Util.class:?]
	... 5 more
```
