### ISSUE TITLE
TileEntityChest cannot be cast to codechicken.enderstorage.tile.TileFrequencyOwner (Crash Report) 1.10.2

### ISSUE THREAD

**Issue by Lightone** [TheCBProject/EnderStorage#8]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCCDeobfPlugin (unknown)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.2.51-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.7.77-universal.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/08/16 12:12 AM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.tileentity.TileEntityChest cannot be cast to codechicken.enderstorage.tile.TileFrequencyOwner
    at codechicken.enderstorage.block.BlockEnderStorage.func_185496_a(BlockEnderStorage.java:231)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
    at net.minecraft.block.Block.func_180646_a(Block.java:375)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
    at net.minecraft.world.World.func_175716_a(World.java:3158)
    at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:125)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:418)
    at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at codechicken.enderstorage.block.BlockEnderStorage.func_185496_a(BlockEnderStorage.java:231)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
    at net.minecraft.block.Block.func_180646_a(Block.java:375)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
    at net.minecraft.world.World.func_175716_a(World.java:3158)
    at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:125)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:418)
    at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Guartinajo'/165, l='MpServer', x=1039,80, y=67,00, z=-308,03]]
    Chunk stats: MultiplayerChunkCache: 42, 42
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 596596 game time, 6750 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 12 total; [EntityBat['Bat'/166, l='MpServer', x=1044,75, y=39,10, z=-316,40], EntityPlayerSP['Guartinajo'/165, l='MpServer', x=1039,80, y=67,00, z=-308,03], EntityBat['Bat'/33287, l='MpServer', x=1019,25, y=49,10, z=-297,25], EntityPig['Pig'/33288, l='MpServer', x=1014,21, y=76,00, z=-283,21], EntityBat['Bat'/201074, l='MpServer', x=1052,25, y=24,10, z=-306,41], EntityBat['Bat'/210, l='MpServer', x=1037,39, y=43,10, z=-308,11], EntityFancyItemFrame['Golden Item Frame'/211, l='MpServer', x=1039,50, y=70,50, z=-309,97], EntityItem['item.item.dyePowder.black'/181073, l='MpServer', x=1071,44, y=37,00, z=-328,88], EntityFancyItemFrame['Golden Item Frame'/212, l='MpServer', x=1039,50, y=69,50, z=-309,97], EntityFancyItemFrame['Golden Item Frame'/213, l='MpServer', x=1039,50, y=68,50, z=-309,97], EntityBat['Bat'/214, l='MpServer', x=1038,56, y=49,10, z=-299,25], EntityBat['Bat'/215, l='MpServer', x=1038,80, y=51,10, z=-295,67]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 401302880 bytes (382 MB) / 1035833344 bytes (987 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.1.2011 Optifine OptiFine_1.10.2_HD_U_C1 25 mods loaded, 25 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAA   Forge{12.18.1.2011} [Minecraft Forge](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAA   CodeChickenCore{2.1.7.77} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   bagginses{2.4.2d} [Bagginses](Bagginses-1.10-3.0.3.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   baublesstuff{2.0.10} [Baubles Stuff](baublesstuff-2.0.10.jar) 
    UCHIJAAAA   ChickenChunks{2.1.2.34} [ChickenChunks](ChickenChunks-1.10.2-2.1.2.34-universal.jar) 
    UCHIJAAAA   EnderStorage{2.1.3.71} [EnderStorage](EnderStorage-1.10.2-2.1.3.71-universal.jar) 
    UCHIJAAAA   excore{1.6.1} [EXCore](Excore-1.6.1-1.10.2%281%29.jar) 
    UCHIJAAAA   JEI{3.7.8.234} [Just Enough Items](jei_1.10.2-3.7.8.234.jar) 
    UCHIJAAAA   FEI{1.0.15} [Forever Enough Items](ForeverEnoughItems-1.0.15-1.10.2.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.6.42} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.6.42.jar) 
    UCHIJAAAA   mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UCHIJAAAA   Neat{1.3-11} [Neat](Neat 1.3-11.jar) 
    UCHIJAAAA   Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAAAA   AS_Ruins{16.2} [Ruins Spawning System](Ruins-1.10.2.jar) 
    UCHIJAAAA   Souls{1.0.3} [Souls](Souls-1.10.2-1.0.3.jar) 
    UCHIJAAAA   tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UCHIJAAAA   totemic{1.9.4-0.7.7} [Totemic](Totemic-1.9.4-0.7.7.jar) 
    UCHIJAAAA   Translocator{2.0.1.26} [Translocator](Translocators-1.9.4-2.0.1.26-universal.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
    UCHIJAAAA   xprings{1.2.0} [Experience Rings](xprings-1.2.0.jar) 
    Loaded coremods (and transformers): 
CCCDeobfPlugin (unknown)

CCLCorePlugin (CodeChickenLib-1.10.2-2.2.2.51-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.7.77-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)`

**Comment by covers1624** [comment]
No idea, if it happens again report it again.
