### ISSUE TITLE
Crash whenever I load my world (IllegalStateException: Already building!)

### ISSUE THREAD

**Issue by recon88** [TheCBProject/EnderStorage#81]
Since yesterday I'm unable to join my world due to a EnderStorage crash:  

```
java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:187)
    at codechicken.enderstorage.client.render.RenderCustomEndPortal.render(RenderCustomEndPortal.java:93)
    at codechicken.enderstorage.client.render.tile.RenderTileEnderChest.renderChest(RenderTileEnderChest.java:43)
    at codechicken.enderstorage.client.render.tile.RenderTileEnderChest.render(RenderTileEnderChest.java:35)
    at codechicken.enderstorage.client.render.tile.RenderTileEnderChest.func_192841_a(RenderTileEnderChest.java:26)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```  

Full Crash Log: https://pastebin.com/UWHyCKZi

**Comment by covers1624** [comment]
Can i have your full launch log? this is likely caused by someone else's TileEntity renderer leaving things in an invalid state.

**Comment by recon88** [comment]
Your are absolutely right. I forgot that I removed Optifine and BetterFPS. The latter was causing weird graphics glitches. I just added Optifne again and it's working fine. Guess that was my bad.

**Comment by covers1624** [comment]
Glad you fixed the issue.
